-- DIBUAT OTOMATIS oleh `pnpm content:sql` dari content/*.json dan messages/id.json. Jangan disunting manual.
-- Upsert idempoten: aman dijalankan ulang. Baris yang dihapus dari konten TIDAK dihapus dari DB
-- (jawaban siswa tetap utuh); tandai saja di konten.

insert into public.units (slug, title, sort_order, learning_objectives, intro) values
  ('u1', 'Benda langit', 1, '["Membedakan bintang, planet, satelit alami, planet kerdil, komet, dan asteroid.","Menjelaskan bahwa Matahari adalah bintang yang membuat cahaya sendiri.","Menjelaskan bahwa Bulan memantulkan cahaya Matahari."]'::jsonb, 'Matahari, planet, planet kerdil, komet, dan asteroid.'),
  ('u2', 'Planet dan karakteristiknya', 2, '["Membandingkan ukuran, suhu, atmosfer, dan permukaan delapan planet.","Menjelaskan mengapa Venus lebih panas daripada Merkurius."]'::jsonb, 'Delapan planet: atmosfer, suhu, ukuran, dan permukaan.'),
  ('u3', 'Zona planet', 3, '["Mengurutkan planet dari yang terdekat sampai terjauh dari Matahari.","Mengelompokkan planet menjadi planet dalam dan planet luar beserta cirinya.","Menunjukkan letak sabuk asteroid sebagai pembatas kedua kelompok."]'::jsonb, 'Planet dalam yang berbatu dan planet luar yang raksasa.'),
  ('u4', 'Meteoroid, meteor, meteorit', 4, '["Membedakan meteoroid, meteor, dan meteorit berdasarkan tempatnya.","Menjelaskan bahwa ''bintang jatuh'' adalah meteor, bukan bintang."]'::jsonb, 'Perjalanan batuan angkasa sampai ke permukaan Bumi.'),
  ('u5', 'Rotasi dan revolusi Bumi', 5, '["Menjelaskan bahwa siang dan malam terjadi karena rotasi Bumi.","Menjelaskan bahwa revolusi Bumi memerlukan sekitar 365¼ hari.","Menjelaskan bahwa musim disebabkan oleh kemiringan sumbu Bumi, bukan jarak ke Matahari."]'::jsonb, 'Kenapa ada siang, malam, dan musim.'),
  ('u6', 'Gerhana', 6, '["Menunjukkan posisi Matahari, Bulan, dan Bumi saat gerhana Matahari dan gerhana Bulan.","Menjelaskan bayangan siapa yang jatuh ke mana pada setiap gerhana.","Menyebutkan cara aman mengamati gerhana Matahari."]'::jsonb, 'Posisi Matahari, Bulan, dan Bumi saat gerhana.')
on conflict (slug) do update set title = excluded.title, sort_order = excluded.sort_order,
  learning_objectives = excluded.learning_objectives, intro = excluded.intro;

insert into public.misconception_targets (code, statement, scientific_explanation, unit_id) values
  ('MK-U1-A', 'Bulan membuat cahayanya sendiri, seperti Matahari.', 'Bulan tidak membuat cahaya. Bulan memantulkan cahaya Matahari.', (select id from public.units where slug = 'u1')),
  ('MK-U1-B', 'Bintang adalah benda kecil, berbeda dengan Matahari.', 'Matahari adalah bintang. Bintang lain tampak kecil karena letaknya sangat jauh.', (select id from public.units where slug = 'u1')),
  ('MK-U2-A', 'Planet yang paling dekat dengan Matahari pasti paling panas.', 'Venus paling panas karena atmosfernya yang tebal menahan panas, walaupun Merkurius lebih dekat ke Matahari.', (select id from public.units where slug = 'u2')),
  ('MK-U3-A', 'Semua planet punya permukaan berbatu seperti Bumi.', 'Hanya planet dalam yang berbatu. Planet luar adalah raksasa gas dan es tanpa permukaan keras.', (select id from public.units where slug = 'u3')),
  ('MK-U3-B', 'Planet dalam dan planet luar ukurannya sama atau tercampur.', 'Planet dalam berukuran kecil dan berbatu; planet luar berukuran raksasa. Sabuk asteroid memisahkan keduanya.', (select id from public.units where slug = 'u3')),
  ('MK-U4-A', 'Semua batuan dari luar angkasa jatuh sampai ke tanah.', 'Hampir semua meteoroid habis terbakar di atmosfer. Hanya sisa yang sampai ke tanah yang disebut meteorit.', (select id from public.units where slug = 'u4')),
  ('MK-U5-A', 'Siang dan malam terjadi karena Matahari mengelilingi Bumi; Matahari menyinari seluruh Bumi sekaligus.', 'Bumi berotasi. Sisi yang menghadap Matahari mengalami siang, sisi yang membelakangi mengalami malam.', (select id from public.units where slug = 'u5')),
  ('MK-U5-B', 'Musim panas terjadi saat Bumi paling dekat dengan Matahari.', 'Musim disebabkan kemiringan sumbu Bumi. Bumi justru paling dekat ke Matahari saat belahan utara mengalami musim dingin.', (select id from public.units where slug = 'u5')),
  ('MK-U6-A', 'Gerhana Bulan terjadi karena awan atau benda lain menutupi Bulan.', 'Saat gerhana Bulan, bayangan Bumi jatuh ke Bulan karena Bumi berada di antara Matahari dan Bulan.', (select id from public.units where slug = 'u6')),
  ('MK-U6-B', 'Saat gerhana Matahari, Bumi yang menghalangi cahaya Matahari.', 'Saat gerhana Matahari, Bulan yang berada di antara Matahari dan Bumi menghalangi cahaya.', (select id from public.units where slug = 'u6'))
on conflict (code) do update set statement = excluded.statement,
  scientific_explanation = excluded.scientific_explanation, unit_id = excluded.unit_id;

insert into public.ar_objects (unit_id, slug, title, sort_order, required, license, attribution, source_url, review_status) values
  ((select id from public.units where slug = 'u1'), 'matahari', 'Matahari', 0, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://nssdc.gsfc.nasa.gov/planetary/factsheet/sunfact.html', 'needs_review'),
  ((select id from public.units where slug = 'u1'), 'bumi', 'Bumi', 1, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://nssdc.gsfc.nasa.gov/planetary/factsheet/', 'needs_review'),
  ((select id from public.units where slug = 'u1'), 'bulan', 'Bulan', 2, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://science.nasa.gov/moon/facts/', 'needs_review'),
  ((select id from public.units where slug = 'u1'), 'pluto', 'Pluto', 3, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://science.nasa.gov/solar-system/planets/what-is-a-planet/', 'needs_review'),
  ((select id from public.units where slug = 'u1'), 'komet', 'Komet', 4, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://science.nasa.gov/solar-system/comets/', 'needs_review'),
  ((select id from public.units where slug = 'u1'), 'asteroid', 'Asteroid', 5, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://science.nasa.gov/solar-system/asteroids/', 'needs_review'),
  ((select id from public.units where slug = 'u2'), 'merkurius', 'Merkurius', 0, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://nssdc.gsfc.nasa.gov/planetary/factsheet/', 'needs_review'),
  ((select id from public.units where slug = 'u2'), 'venus', 'Venus', 1, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://nssdc.gsfc.nasa.gov/planetary/factsheet/', 'needs_review'),
  ((select id from public.units where slug = 'u2'), 'bumi', 'Bumi', 2, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://nssdc.gsfc.nasa.gov/planetary/factsheet/', 'needs_review'),
  ((select id from public.units where slug = 'u2'), 'mars', 'Mars', 3, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://nssdc.gsfc.nasa.gov/planetary/factsheet/', 'needs_review'),
  ((select id from public.units where slug = 'u2'), 'jupiter', 'Jupiter', 4, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://nssdc.gsfc.nasa.gov/planetary/factsheet/', 'needs_review'),
  ((select id from public.units where slug = 'u2'), 'saturnus', 'Saturnus', 5, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://nssdc.gsfc.nasa.gov/planetary/factsheet/', 'needs_review'),
  ((select id from public.units where slug = 'u2'), 'uranus', 'Uranus', 6, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://nssdc.gsfc.nasa.gov/planetary/factsheet/', 'needs_review'),
  ((select id from public.units where slug = 'u2'), 'neptunus', 'Neptunus', 7, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://nssdc.gsfc.nasa.gov/planetary/factsheet/', 'needs_review'),
  ((select id from public.units where slug = 'u3'), 'zona-dalam', 'Planet dalam', 0, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://science.nasa.gov/solar-system/planets/', 'needs_review'),
  ((select id from public.units where slug = 'u3'), 'sabuk-asteroid', 'Sabuk asteroid', 1, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://science.nasa.gov/solar-system/asteroids/', 'needs_review'),
  ((select id from public.units where slug = 'u3'), 'zona-luar', 'Planet luar', 2, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://science.nasa.gov/solar-system/planets/', 'needs_review'),
  ((select id from public.units where slug = 'u4'), 'meteoroid', 'Meteoroid', 0, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://science.nasa.gov/solar-system/meteors-meteorites/', 'needs_review'),
  ((select id from public.units where slug = 'u4'), 'meteor', 'Meteor', 1, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://science.nasa.gov/solar-system/meteors-meteorites/', 'needs_review'),
  ((select id from public.units where slug = 'u4'), 'meteorit', 'Meteorit', 2, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://science.nasa.gov/solar-system/meteors-meteorites/', 'needs_review'),
  ((select id from public.units where slug = 'u5'), 'rotasi', 'Rotasi Bumi', 0, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://astroedu.iau.org/en/activities/why-do-we-have-day-and-night/', 'needs_review'),
  ((select id from public.units where slug = 'u5'), 'revolusi', 'Revolusi Bumi', 1, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://nssdc.gsfc.nasa.gov/planetary/factsheet/earthfact.html', 'needs_review'),
  ((select id from public.units where slug = 'u6'), 'gerhana-matahari', 'Gerhana Matahari', 0, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://science.nasa.gov/eclipses/types/', 'needs_review'),
  ((select id from public.units where slug = 'u6'), 'gerhana-bulan', 'Gerhana Bulan', 1, true, 'Karya sendiri — prosedural (lihat assets/manifest.json)', 'Ilustrasi ARSSMED', 'https://science.nasa.gov/eclipses/types/', 'needs_review')
on conflict (unit_id, slug) do update set title = excluded.title, sort_order = excluded.sort_order,
  required = excluded.required, license = excluded.license, attribution = excluded.attribution,
  source_url = excluded.source_url, review_status = excluded.review_status;

insert into public.prediction_items (key, unit_id, sort_order, stem, options, correct_key, reveal_text, misconception_code, misconception_option) values
  ('u1-cahaya-bulan', (select id from public.units where slug = 'u1'), 0, 'Bulan tampak terang di langit malam. Menurutmu, dari mana cahaya Bulan berasal?', '[{"key":"A","text":"Bulan membuat cahayanya sendiri."},{"key":"B","text":"Bulan memantulkan cahaya Matahari."},{"key":"C","text":"Bulan memantulkan cahaya bintang-bintang."}]'::jsonb, 'B', 'Ternyata Bulan tidak membuat cahaya sendiri. Bulan bersinar karena memantulkan cahaya Matahari.', 'MK-U1-A', 'A'),
  ('u1-bintang-dekat', (select id from public.units where slug = 'u1'), 1, 'Bayangkan kamu terbang mendekati sebuah bintang yang tampak kecil di langit malam. Bintang itu akan tampak seperti apa?', '[{"key":"A","text":"Tetap kecil seperti titik."},{"key":"B","text":"Sangat besar dan terang, seperti Matahari."},{"key":"C","text":"Tidak bercahaya lagi."}]'::jsonb, 'B', 'Ternyata Matahari juga bintang. Bintang lain tampak kecil hanya karena letaknya sangat jauh.', 'MK-U1-B', 'A'),
  ('u2-merkurius-venus', (select id from public.units where slug = 'u2'), 0, 'Merkurius adalah planet terdekat dari Matahari, sedangkan Venus ada di urutan kedua. Menurutmu, bagaimana suhu rata-rata permukaan keduanya?', '[{"key":"A","text":"Merkurius lebih panas karena lebih dekat ke Matahari."},{"key":"B","text":"Venus lebih panas."},{"key":"C","text":"Suhu keduanya sama."}]'::jsonb, 'B', 'Ternyata Venus lebih panas, sekitar 464 °C, walaupun Merkurius lebih dekat. Atmosfer Venus yang tebal menahan panas.', 'MK-U2-A', 'A'),
  ('u3-mendarat-jupiter', (select id from public.units where slug = 'u3'), 0, 'Seandainya sebuah wahana mendarat di Jupiter, di atas apa wahana itu akan berada?', '[{"key":"A","text":"Tanah berbatu yang keras, seperti di Bumi."},{"key":"B","text":"Tidak ada tanah keras; yang ada lapisan gas tebal."},{"key":"C","text":"Lautan air seperti di Bumi."}]'::jsonb, 'B', 'Ternyata Jupiter tidak punya permukaan keras. Jupiter dan Saturnus adalah raksasa gas.', 'MK-U3-A', 'A'),
  ('u3-ukuran-kelompok', (select id from public.units where slug = 'u3'), 1, 'Dibandingkan planet-planet yang jauh dari Matahari, planet-planet yang dekat dengan Matahari ukurannya…', '[{"key":"A","text":"lebih besar."},{"key":"B","text":"lebih kecil."},{"key":"C","text":"sama besar."}]'::jsonb, 'B', 'Ternyata planet dalam jauh lebih kecil. Bumi, planet dalam terbesar, masih lebih kecil daripada Neptunus, planet luar terkecil.', 'MK-U3-B', 'C'),
  ('u4-nasib-batuan', (select id from public.units where slug = 'u4'), 0, 'Setiap hari banyak batuan kecil dari luar angkasa masuk ke lapisan udara Bumi. Menurutmu, apa yang terjadi pada kebanyakan batuan itu?', '[{"key":"A","text":"Semuanya jatuh ke tanah."},{"key":"B","text":"Kebanyakan habis terbakar di udara."},{"key":"C","text":"Memantul kembali ke luar angkasa."}]'::jsonb, 'B', 'Ternyata hampir semua batuan itu habis terbakar di atmosfer dan tampak sebagai meteor. Hanya sisanya yang sampai ke tanah yang disebut meteorit.', 'MK-U4-A', 'A'),
  ('u5-sisi-berlawanan', (select id from public.units where slug = 'u5'), 0, 'Saat di Indonesia siang hari, bagaimana keadaan di tempat yang letaknya tepat di sisi Bumi yang berlawanan?', '[{"key":"A","text":"Juga siang, karena Matahari menyinari seluruh Bumi sekaligus."},{"key":"B","text":"Malam hari."},{"key":"C","text":"Sore hari, Matahari sedang terbenam."}]'::jsonb, 'B', 'Ternyata cahaya Matahari hanya mengenai separuh Bumi. Saat Indonesia siang, sisi yang berlawanan sedang malam.', 'MK-U5-A', 'A'),
  ('u5-dekat-januari', (select id from public.units where slug = 'u5'), 1, 'Bumi berada paling dekat dengan Matahari setiap awal Januari. Menurutmu, musim apa yang sedang terjadi di belahan Bumi utara, misalnya di Jepang?', '[{"key":"A","text":"Musim panas, karena Bumi paling dekat ke Matahari."},{"key":"B","text":"Musim dingin."},{"key":"C","text":"Tidak ada musim."}]'::jsonb, 'B', 'Ternyata saat itu belahan utara mengalami musim dingin. Musim disebabkan kemiringan sumbu Bumi, bukan jaraknya ke Matahari.', 'MK-U5-B', 'A'),
  ('u6-penutup-bulan', (select id from public.units where slug = 'u6'), 0, 'Saat gerhana Bulan, Bulan purnama menjadi gelap atau kemerahan. Menurutmu, apa yang menutupi Bulan?', '[{"key":"A","text":"Awan tebal di langit."},{"key":"B","text":"Bayangan Bumi."},{"key":"C","text":"Bayangan Matahari."}]'::jsonb, 'B', 'Ternyata yang menutupi Bulan adalah bayangan Bumi. Bumi berada di antara Matahari dan Bulan.', 'MK-U6-A', 'A'),
  ('u6-penghalang-matahari', (select id from public.units where slug = 'u6'), 1, 'Saat gerhana Matahari total, siang hari mendadak gelap sebentar. Menurutmu, benda apa yang menghalangi cahaya Matahari?', '[{"key":"A","text":"Bumi."},{"key":"B","text":"Bulan."},{"key":"C","text":"Awan hitam."}]'::jsonb, 'B', 'Ternyata yang menghalangi adalah Bulan. Bulan lewat di antara Matahari dan Bumi, lalu bayangannya jatuh ke Bumi.', 'MK-U6-B', 'A')
on conflict (key) do update set unit_id = excluded.unit_id, sort_order = excluded.sort_order, stem = excluded.stem,
  options = excluded.options, correct_key = excluded.correct_key, reveal_text = excluded.reveal_text,
  misconception_code = excluded.misconception_code, misconception_option = excluded.misconception_option;
